// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Simulation

struct RigidbodyData
{
	float minX, maxX, minY, maxY, minZ, maxZ;
	float4x4 transformInv, transform;

	float3 velocity, acceleration, force;
};

RWTexture3D<float4> UniformGrid;
RWStructuredBuffer<float4> Positions;
RWStructuredBuffer<RigidbodyData> Ridigbodies;

[numthreads(10, 10, 10)]
void Simulation(uint3 id : SV_DispatchThreadID)
{

}
